version: 0.0
os: linux
runas: root

files:
  - source: /
    destination: /home/ubuntu/node-application/
    overwrite: true

hooks:
  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
